# Generated by Django 4.2.7 on 2026-01-23 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_hash', models.CharField(help_text="Hashed OTP using Django's password hasher for security", max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when OTP was created')),
                ('expires_at', models.DateTimeField(help_text='Timestamp when OTP expires (5 minutes from creation)')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this OTP has been used for authentication')),
                ('user', models.ForeignKey(help_text='User this OTP belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'expires_at'], name='accounts_ot_user_id_211b3d_idx')],
            },
        ),
    ]
