# Generated by Django 5.2.9 on 2026-03-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otp_email'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otp',
            new_name='accounts_ot_email_6ea7c3_idx',
            old_name='accounts_ot_email_123abc_idx',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(help_text='Timestamp when OTP expires (10 minutes from creation)'),
        ),
    ]
