# Generated by Django 5.2.9 on 2026-04-02 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_accounts_ot_email_123abc_idx_accounts_ot_email_6ea7c3_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(max_length=100, unique=True)),
                ('coin', models.CharField(default='BTCUSDT', max_length=50)),
                ('side', models.CharField(help_text='Buy or Sell', max_length=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=30)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('total_value', models.DecimalField(decimal_places=8, help_text='price * amount', max_digits=30)),
                ('profit_loss', models.DecimalField(decimal_places=8, default=0.0, max_digits=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('balance', models.DecimalField(decimal_places=8, default=1000000.0, help_text='Primary USDT Balance', max_digits=30)),
                ('btc_balance', models.DecimalField(decimal_places=8, default=0.0, help_text='Secondary BTC Balance', max_digits=30)),
                ('total_deposits', models.DecimalField(decimal_places=8, default=0.0, max_digits=30)),
                ('total_withdrawals', models.DecimalField(decimal_places=8, default=0.0, max_digits=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
