# Generated by Django 5.2.9 on 2026-04-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_trade_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='event_type',
            field=models.CharField(default='spot_fill', help_text='spot_fill, futures_open, futures_close', max_length=30),
        ),
        migrations.AddField(
            model_name='trade',
            name='market_type',
            field=models.CharField(default='spot', help_text='spot or futures', max_length=20),
        ),
    ]
