# Generated by Django 5.2.9 on 2026-04-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_walletasset_wallettransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='trade',
            name='event_type',
            field=models.CharField(choices=[('spot_fill', 'Spot Fill'), ('futures_open', 'Futures Open'), ('futures_close', 'Futures Close')], default='spot_fill', help_text='spot_fill, futures_open, futures_close', max_length=30),
        ),
        migrations.AlterField(
            model_name='trade',
            name='market_type',
            field=models.CharField(choices=[('spot', 'Spot'), ('futures', 'Futures')], default='spot', help_text='spot or futures', max_length=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='side',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Long', 'Long'), ('Short', 'Short'), ('Close', 'Close')], help_text='Buy, Sell, Long, Short or Close', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], default='completed', max_length=30),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'timestamp'], name='accounts_tr_user_id_43656f_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['coin', 'timestamp'], name='accounts_tr_coin_dae4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['market_type', 'event_type'], name='accounts_tr_market__b828f0_idx'),
        ),
    ]
