# Generated by Django 5.2.9 on 2026-04-02 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_trade_options_alter_trade_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='event_type',
            field=models.CharField(choices=[('spot_fill', 'Spot Fill'), ('margin_open', 'Margin Open'), ('margin_close', 'Margin Close'), ('futures_open', 'Futures Open'), ('futures_close', 'Futures Close')], default='spot_fill', help_text='spot_fill, futures_open, futures_close', max_length=30),
        ),
        migrations.AlterField(
            model_name='trade',
            name='market_type',
            field=models.CharField(choices=[('spot', 'Spot'), ('margin', 'Margin'), ('futures', 'Futures')], default='spot', help_text='spot or futures', max_length=20),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(default='BTCUSDT', max_length=50)),
                ('market_type', models.CharField(choices=[('margin', 'Margin'), ('futures', 'Futures')], max_length=20)),
                ('side', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=30)),
                ('leverage', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('margin', models.DecimalField(decimal_places=8, default=0.0, max_digits=30)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('close_price', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('realized_pnl', models.DecimalField(decimal_places=8, default=0.0, max_digits=30)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='accounts.wallet')),
            ],
            options={
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['user', 'market_type', 'status'], name='accounts_po_user_id_00c7c8_idx'), models.Index(fields=['symbol', 'status'], name='accounts_po_symbol_c7d433_idx')],
            },
        ),
    ]
