# Generated by Django 5.2.9 on 2026-04-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_trade_event_type_alter_trade_market_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='tx_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('spot_buy_quote', 'Spot Buy (Quote Debit)'), ('spot_buy_asset', 'Spot Buy (Asset Credit)'), ('spot_sell_asset', 'Spot Sell (Asset Debit)'), ('spot_sell_quote', 'Spot Sell (Quote Credit)'), ('margin_open', 'Margin Open (USDT Debit)'), ('margin_close', 'Margin Close (USDT Credit)'), ('margin_close_loss', 'Margin Close (USDT Debit)'), ('futures_open', 'Futures Open (USDT Debit)'), ('futures_close', 'Futures Close (USDT Credit)'), ('futures_close_loss', 'Futures Close (USDT Debit)')], max_length=20),
        ),
    ]
