# Generated by Django 5.2.9 on 2026-04-10 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_wallettransaction_tx_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='fee',
            field=models.DecimalField(decimal_places=8, default=0.0, help_text='Trading fee charged (in USDT)', max_digits=30),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_fees_paid',
            field=models.DecimalField(decimal_places=8, default=0.0, help_text='Cumulative trading/withdrawal fees paid by this user', max_digits=30),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='fee',
            field=models.DecimalField(decimal_places=8, default=0.0, help_text='Fee charged for this transaction', max_digits=30),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='tx_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('spot_buy_quote', 'Spot Buy (Quote Debit)'), ('spot_buy_asset', 'Spot Buy (Asset Credit)'), ('spot_sell_asset', 'Spot Sell (Asset Debit)'), ('spot_sell_quote', 'Spot Sell (Quote Credit)'), ('margin_open', 'Margin Open (USDT Debit)'), ('margin_close', 'Margin Close (USDT Credit)'), ('margin_close_loss', 'Margin Close (USDT Debit)'), ('futures_open', 'Futures Open (USDT Debit)'), ('futures_close', 'Futures Close (USDT Credit)'), ('futures_close_loss', 'Futures Close (USDT Debit)'), ('trading_fee', 'Trading Fee'), ('withdrawal_fee', 'Withdrawal Fee')], max_length=20),
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('asset', models.CharField(default='USDT', max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, help_text='Always positive; direction indicated by entry_type', max_digits=30)),
                ('balance_after', models.DecimalField(decimal_places=8, help_text='Wallet balance in this asset after this entry', max_digits=30)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counterpart', models.ForeignKey(blank=True, help_text='The other half of this double-entry pair', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_entry', to='accounts.ledgerentry')),
                ('reference_tx', models.ForeignKey(blank=True, help_text='The WalletTransaction that triggered this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='accounts.wallettransaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='accounts.wallet')),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'asset', 'created_at'], name='accounts_le_wallet__d3f38c_idx'), models.Index(fields=['entry_type', 'created_at'], name='accounts_le_entry_t_1efc04_idx')],
            },
        ),
    ]
