# Generated by Django 5.2.9 on 2026-04-12 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_kyc_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google')], max_length=30)),
                ('provider_uid', models.CharField(help_text="Provider unique user ID (Google 'sub' claim)", max_length=255)),
                ('email', models.EmailField(help_text='Email from the OAuth provider', max_length=254)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
                'indexes': [models.Index(fields=['provider', 'email'], name='accounts_so_provide_b76d35_idx')],
                'unique_together': {('provider', 'provider_uid')},
            },
        ),
    ]
